name: reco-gym
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - notebook=5.4.0
  - matplotlib=2.1.0
  - numpy=1.13.3
  - python=3.6.3
  - pandas=0.23.4
  - scipy=1.0.0
  - pytorch=0.4.1
  - rpy2=2.9.1
  # - gym=X.Y.Z conda support is missing, use `pip install gym` instead
  - pip:
    - torch==0.4.1