name: reco-gym
channels:
  - pytorch
  - anaconda
  - defaults
  - intel
dependencies:
  - notebook
  - matplotlib
  - intelpython3_full
  - pandas
  - pytorch
  - rpy2
  # - gym=X.Y.Z conda support is missing, use `pip install gym` instead
  - pip:
    - gym
    - absl-py
    - numba
    - tqdm
    - datetime
